### PR TITLE
Do not remove the figure-html subdir

### LINKED ISSUE #38: Support for widgetframe
Similar to rstudio/bookdown#271 I need a way to move the child widget HTML and lib files over to the `bookdown` directory and subsequently to `public` directory under the proper sub directory.

Current behavior is the child html is copied under directory 'public/1/01/01/index.html' and widget_libs folder is copied under `public/post/. Both these behaviors are not correct.

The child widget and its widget_libs directory should be copied over to where the parent HTML is.

### PR DESCRIPTION
**Pull request by yihui**
This will fix rstudio/blogdown#38.

### CODE REVIEW

**Comment by bhaskarvk** [comment]
Thanks!  I am traveling this whole week but I will get back to this over the weekend. And thanks much for your support.

**Comment by yihui** [comment]
Sounds good. It is a simple change but you may need some time to think about the consequences. I have tested both blogdown and other R Markdown documents, and they seem to still work well.

**Comment by bhaskarvk** [comment]
Yeah it's mostly to test out every possible R Markdown format.

**Comment by bhaskarvk** [comment]
I am testing this now, and so far works with rmarkdown, rmarkdown-website, xaringan, flexdashboard.
But I still require the hackish way of using a Makefile and specifying widgets_dir for bookdown. Otherwise the dependencies are not moved to the final book output directory.
Tomorrow I'll check for the blogdown part.

**Comment by yihui** [comment]
I'll address the bookdown issue in bookdown when I have more time. You won't need any changes in widgetframe.

**Comment by bhaskarvk** [comment]
I just tested this with blogdown and it works perfectly if the method is 'html', but doesn't work if the method is `html_encoded`. The widgets folder is neither to be found under `static` folder and hence also not present under the `public` folder.
I am fine documenting this limitation, but it would be awesome if we can support `html_encoded` too.

**Comment by yihui** [comment]
You are correct. It does not work with `html_encoded`. I don't think there will be more than three people in the world who would use `html_encoded`. The benefit is minimal, and the disadvantages sound bad enough.

**Comment by bhaskarvk** [comment]
@yihui Thanks for the fix. One more small point the URL to the iframed widget HTML works only when the site is deployed on the root. When the site is deployed in a level below the root, i.e. http://www.abcd.com/blog/, then the URL to the child widget HTMLs is wrong. This is not a big issue as I really doubt if many people will deploy their blogs to non root path.

Thanks again for your help!

**Comment by elliottmorris** [comment]
I'm still getting an error in my file, and I think it has something to do with @bhaskarvk most recent comment. 

I'm trying to use a widgetframe with datatable in a .Rmarkdown that lies within my /pages subdirectory. The frame just pulls up my 404 page. I'm also running on the future-imperfect theme, which I know has had some trouble in the past. 

Any solutions?

**Comment by yihui** [comment]
It should work unless you have set `relativesurl = true` in config.toml. Try to remove this option or set it to `false`, then `blogdown::build_site()` with the latest version of blogdown.

**Comment by bhaskarvk** [comment]
@elliottmorris could you share your config files and where you deploy your site?

**Comment by elliottmorris** [comment]
I tried setting `relativesurl = false` and updating both `blogdown` and `widgetframe` to their latest versions, but still to no avail. 

Attempting to display the widget at http://www.thecrosstab.com/trump-tracker/. Attached is my config.toml in text format.
[config_toml.txt](https://github.com/bhaskarvk/widgetframe/files/1209822/config_toml.txt)



EDIT: there seems to have been a corrupted download for blogdown. Have reinstalled, restarted, rebuilt and it all works now. Thanks for the tip on relativesurl.

**Comment by yihui** [comment]
Okay, glad to hear that.

**Comment by bhaskarvk** [comment]
FWIW I don't think `relativeurl` was your problem to begin with. It must have been sometihng to do with corrupt blogdown install. @yihui I double checked and regardless of what relativeurl is set to the url attribute for the iframe source starts with an absolute path. so something like '/post/....' which works fine when the site is deployed at the root of a webserver which is what @elliottmorris  is doing. 
But if the site is deployed one level down so e.g. `www.abcd.com/blog/` instead of `www.abcd.com` then it won't work coz the URL is not changed to /blog/post as it should be.

**Comment by yihui** [comment]
@bhaskarvk When `relativeurls = false`, you should get `/blog/post/...` instead of `/post/...`. Could you test with the latest version of blogdown?

**Comment by elliottmorris** [comment]
I actually don't have a /blog/ folder and set permalink to match Jekyll structure (:year/:month/:day/:slug) so this doesn't show up either way

**Comment by B2Silva** [comment]
> FWIW I don't think `relativeurl` was your problem to begin with. It must have been sometihng to do with corrupt blogdown install. @yihui I double checked and regardless of what relativeurl is set to the url attribute for the iframe source starts with an absolute path. so something like '/post/....' which works fine when the site is deployed at the root of a webserver which is what @elliottmorris is doing.
> But if the site is deployed one level down so e.g. `www.abcd.com/blog/` instead of `www.abcd.com` then it won't work coz the URL is not changed to /blog/post as it should be.

I am suffering from the same behavior.
But I am using "hugo-creative-portfolio-theme".
Basically, I am deploying one level down www.abcd.com/website instead of www.abcd.com and the URL inside the widgetframe is pointing to the www.abcd.com.
Any solution?

**Comment by elliottmorris** [comment]
IIRC, you should specify the subdirectory in the `baseURL`  field of your `config.toml`, IE:

`baseURL: abcd.com/website/`


This is covered more extensively in @yihui’s blowdown book: https://bookdown.org/yihui/blogdown/configuration.html

**Pull request merged**
